/-
Copyright (c) 2026 Kuldeep S. Meel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kuldeep S. Meel
-/
import Arlib.Computation

/-!
# Computation audit — the seal

`Arlib.Computation`'s cost bounds are honest only if a client cannot obtain the
contents of a machine word, or move the machine's state, without paying for it.
Most of that is enforced by the compiler: `Word` and `RAM` have private
constructors, `Word`'s field is private, and `Word.toNat` is `noncomputable`, so
a program that inspects a word fails to compile. `ArlibTest/Computation.lean` §3
checks each of those by writing the cheat and confirming it is rejected.

Two routes are *not* closed by the compiler, and this script is what closes them.

**`Word.casesOn` and friends.** A structure's `casesOn` is generated public even
when its constructor is private, and unlike `rec` it is compiled. So
`Word.casesOn x (fun v => v)` extracts the field. No algorithm has any reason to
mention it.

**An explicit `noncomputable def`.** Marking a program `noncomputable` silences
the compiler error that stops it from reading a word. A specification may be
noncomputable; an algorithm may not.

Run it with

```bash
lake env lean scripts/ComputationAudit.lean
```

which exits non-zero if either invariant is broken. CI runs exactly this
alongside `AxiomAudit.lean`.

The audit is deliberately narrow. It does not try to decide whether a definition
"is an algorithm"; it checks the two syntactic facts that are actually
load-bearing, and it names the offender when it fails.
-/

open Lean Elab Command

namespace Arlib.ComputationAudit

/-- The eliminators that would project a `Word`'s private field back out.  None
of them belongs in an algorithm. -/
def forbidden : List Name :=
  [``Arlib.Computation.Word.casesOn, ``Arlib.Computation.Word.rec,
   ``Arlib.Computation.Word.recOn]

/-- Declarations in the area that are *allowed* to be noncomputable, because they
are specification vocabulary rather than programs.

`Word.toNat` is the view a theorem needs and is noncomputable precisely so that a
program cannot use it; the rest are predicates and cost accounting. -/
def specOnly : List Name :=
  [``Arlib.Computation.Word.toNat]

/-- Declarations the elaborator generates for every inductive type.  They are
nobody's algorithm, and `noConfusion` in particular necessarily mentions the
constructor, so auditing them would report a breach that no author wrote. -/
def autoGenerated : List Name :=
  [`noConfusion, `noConfusionType, `casesOn, `recOn, `rec, `brecOn, `below,
   `ndrec, `injEq, `inj, `sizeOf_spec, `mk]

/-- Every non-internal, author-written declaration under `Arlib.Computation`. -/
def areaDecls (env : Environment) : Array Name := Id.run do
  let mut out : Array Name := #[]
  for (n, _) in env.constants.toList do
    if n.isInternal then continue
    if autoGenerated.contains n.getRoot || autoGenerated.contains (n.componentsRev.headD .anonymous)
      then continue
    if (`Arlib.Computation).isPrefixOf n then out := out.push n
  return out

/-- Whether `n`'s value mentions one of the forbidden eliminators. -/
def usesForbidden (env : Environment) (n : Name) : Bool := Id.run do
  match env.find? n with
  | none => return false
  | some ci =>
    match ci.value? with
    | none => return false
    | some v =>
      for c in v.getUsedConstants do
        if forbidden.contains c then return true
      return false

end Arlib.ComputationAudit

open Arlib.ComputationAudit in
run_cmd do
  let env ← getEnv
  let decls := areaDecls env
  let mut leaks : Array Name := #[]
  let mut nonComp : Array Name := #[]
  for n in decls do
    if forbidden.contains n then continue
    if usesForbidden env n then leaks := leaks.push n
    if Lean.isNoncomputable env n && !(specOnly.contains n) then
      -- theorems and other propositions carry no executable content
      match env.find? n with
      | some ci =>
        let isProp ← liftTermElabM do
          Meta.isProp ci.type
        if !isProp then nonComp := nonComp.push n
      | none => pure ()
  unless leaks.isEmpty do
    logError m!"Seal breach: {leaks.size} declaration(s) project a Word's field \
      through an eliminator: {leaks.toList}"
  unless nonComp.isEmpty do
    logError m!"Seal breach: {nonComp.size} noncomputable definition(s) outside \
      the specification vocabulary: {nonComp.toList}.  A noncomputable program \
      can read a word without charging for it; add it to `specOnly` only if it \
      is genuinely specification-only."
  if leaks.isEmpty && nonComp.isEmpty then
    logInfo m!"Computation audit clean: {decls.size} declarations, \
      no eliminator leak, no noncomputable program."
